live_config_reload: true

env:
  TERM: "xterm-256color"

window:
  option_as_alt: OnlyLeft
  decorations: buttonless
  startup_mode: Maximized
  padding:
    x: 10
    y: 10

scrolling:
  history: 99999

mouse:
  selection:
    save_to_clipboard: true

font:
  size: 16
  normal:
    family: JetBrainsMono Nerd Font

key_bindings:
  - { key: N,          mods: Command,          action: CreateNewWindow                       }
  - { key: Q,          mods: Command,          action: Quit                                  }
  - { key: Space,      mods: Control,          chars: "\x00"                                 }
  - { key: Grave,      mods: Alt,              chars: "\x1b`"                                }
  - { key: Grave,      mods: Alt|Shift,        chars: "\x1b~"                                }
  - { key: Period,     mods: Alt,              chars: "\x1b."                                }
  - { key: Period,     mods: Alt|Shift,        chars: "\x1b>"                                }
  - { key: Comma,      mods: Alt|Shift,        chars: "\x1b<"                                }
  - { key: Minus,      mods: Alt|Shift,        chars: "\x1b_"                                }
  - { key: Backslash,  mods: Alt,              chars: "\x1b\\"                               }
  - { key: Backslash,  mods: Alt|Shift,        chars: "\x1b|"                                }
  - { key: Slash,      mods: Alt,              chars: "\x1b/"                                }
  - { key: RBracket,   mods: Alt,              chars: "\x1b]"                                }
  - { key: LBracket,   mods: Alt,              chars: "\x1b["                                }
  - { key: Tab,        mods: Alt,              chars: "\t"                                   }
  - { key: Tab,        mods: Alt,              chars: "\x1b\t"                               }
  - { key: Tab,        mods: Alt|Shift,        chars: "\x1b\x1b[Z"                           }
  - { key: A,          mods: Alt,              chars: "\x1ba"                                }
  - { key: B,          mods: Alt,              chars: "\x1bb"                                }
  - { key: C,          mods: Alt,              chars: "\x1bc"                                }
  - { key: D,          mods: Alt,              chars: "\x1bd"                                }
  - { key: E,          mods: Alt,              chars: "\x1be"                                }
  - { key: F,          mods: Alt,              chars: "\x1bf"                                }
  - { key: G,          mods: Alt,              chars: "\x1bg"                                }
  - { key: H,          mods: Alt,              chars: "\x1bh"                                }
  - { key: I,          mods: Alt,              chars: "\x1bi"                                }
  - { key: J,          mods: Alt,              chars: "\x1bj"                                }
  - { key: K,          mods: Alt,              chars: "\x1bk"                                }
  - { key: L,          mods: Alt,              chars: "\x1bl"                                }
  - { key: M,          mods: Alt,              chars: "\x1bm"                                }
  - { key: N,          mods: Alt,              chars: "\x1bn"                                }
  - { key: O,          mods: Alt,              chars: "\x1bo"                                }
  - { key: P,          mods: Alt,              chars: "\x1bp"                                }
  - { key: P,          mods: Control|Shift,    chars: "\x1b[80;6u"                           }
  - { key: Q,          mods: Alt,              chars: "\x1bq"                                }
  - { key: R,          mods: Alt,              chars: "\x1br"                                }
  - { key: S,          mods: Alt,              chars: "\x1bs"                                }
  - { key: T,          mods: Alt,              chars: "\x1bt"                                }
  - { key: U,          mods: Alt,              chars: "\x1bu"                                }
  - { key: V,          mods: Alt,              chars: "\x1bv"                                }
  - { key: W,          mods: Alt,              chars: "\x1bw"                                }
  - { key: X,          mods: Alt,              chars: "\x1bx"                                }
  - { key: Y,          mods: Alt,              chars: "\x1by"                                }
  - { key: Z,          mods: Alt,              chars: "\x1bz"                                }
  - { key: A,          mods: Alt|Shift,        chars: "\x1bA"                                }
  - { key: B,          mods: Alt|Shift,        chars: "\x1bB"                                }
  - { key: C,          mods: Alt|Shift,        chars: "\x1bC"                                }
  - { key: D,          mods: Alt|Shift,        chars: "\x1bD"                                }
  - { key: E,          mods: Alt|Shift,        chars: "\x1bE"                                }
  - { key: F,          mods: Alt|Shift,        chars: "\x1bF"                                }
  - { key: G,          mods: Alt|Shift,        chars: "\x1bG"                                }
  - { key: H,          mods: Alt|Shift,        chars: "\x1bH"                                }
  - { key: I,          mods: Alt|Shift,        chars: "\x1bI"                                }
  - { key: J,          mods: Alt|Shift,        chars: "\x1bJ"                                }
  - { key: K,          mods: Alt|Shift,        chars: "\x1bK"                                }
  - { key: L,          mods: Alt|Shift,        chars: "\x1bL"                                }
  - { key: M,          mods: Alt|Shift,        chars: "\x1bM"                                }
  - { key: N,          mods: Alt|Shift,        chars: "\x1bN"                                }
  - { key: O,          mods: Alt|Shift,        chars: "\x1bO"                                }
  - { key: P,          mods: Alt|Shift,        chars: "\x1bP"                                }
  - { key: Q,          mods: Alt|Shift,        chars: "\x1bQ"                                }
  - { key: R,          mods: Alt|Shift,        chars: "\x1bR"                                }
  - { key: S,          mods: Alt|Shift,        chars: "\x1bS"                                }
  - { key: T,          mods: Alt|Shift,        chars: "\x1bT"                                }
  - { key: U,          mods: Alt|Shift,        chars: "\x1bU"                                }
  - { key: V,          mods: Alt|Shift,        chars: "\x1bV"                                }
  - { key: W,          mods: Alt|Shift,        chars: "\x1bW"                                }
  - { key: X,          mods: Alt|Shift,        chars: "\x1bX"                                }
  - { key: Y,          mods: Alt|Shift,        chars: "\x1bY"                                }
  - { key: Z,          mods: Alt|Shift,        chars: "\x1bZ"                                }
  # disable search shortcuts
  - { key: F,          mods: Command,          action: ReceiveChar                           }
  - { key: B,          mods: Command,          action: ReceiveChar                           }


# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161e'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

  indexed_colors:
    - { index: 16, color: '0xff9e64' }
    - { index: 17, color: '0xdb4b4b' }
